### ISSUE TITLE
Bug in the computation of PLP likelihood

### ISSUE THREAD

**Issue by SamuelGabriel** [tomsilver/policies_logic_programs#2]
Hey Tom,

I work with your code right now, and I like it. I just came around a critical bug though, I think. You assign 0. log prob to all programs incorporating the right solution an -inf to all others. It is just an indentation problem after the line I marked. Am I right? Did you use that code for your paper and still got the good results?

Best,

Sam

https://github.com/tomsilver/policies_logic_programs/blob/761f925d4031bcd81b19e6356a8756fb87e49e51/pipeline.py#L290

**Comment by tomsilver** [comment]
Hey Sam,

Thanks for taking a look at the code and for reaching out! You're right, that looks like an indentation error to me. We did get good results with that, which is interesting -- it suggests that a graded likelihood is not so important. After fixing, I would hope that the results would even improve further, but I suspect that they will actually stay about the same, since I think a lot of the work is being done by the decision tree learning and the prior. 

After making [the correction](https://github.com/tomsilver/policies_logic_programs/commit/7b83f48d4c4a24fcefea6fae142f5d829c2c1d74) I don't see any obvious changes in the results for TwoPileNim or Chase. (The other games will take a bit longer to verify.) Thanks very much for catching this and please be in touch if you see anything else or have any questions!

Best,

Tom
